---
# handlers file for alerta

- name: restart alerta
  become: true
  systemd:
    name: "{{ alerta_systemd_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart alerta-webaddon
  become: true
  systemd:
    name: "{{ alerta_webaddon_systemd_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
